/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_eunchuljeon_opencvndktest_MainActivity */

#ifndef _Included_com_eunchuljeon_opencvndktest_MainActivity
#define _Included_com_eunchuljeon_opencvndktest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eunchuljeon_opencvndktest_MainActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_eunchuljeon_opencvndktest_MainActivity_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
