/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_naver_android_pholar_util_pholarimageprocess_PholarImageProcessWrapper */

#ifndef _Included_com_naver_android_pholar_util_pholarimageprocess_PholarImageProcessWrapper
#define _Included_com_naver_android_pholar_util_pholarimageprocess_PholarImageProcessWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_naver_android_pholar_util_pholarimageprocess_PholarImageProcessWrapper
 * Method:    getAvgColor
 * Signature: (J)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_naver_android_pholar_util_pholarimageprocess_PholarImageProcessWrapper_getAvgColor
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
